#!/bin/sh -e

case "$1" in
    failed-upgrade|abort-install|abort-upgrade|disappear|upgrade)
    ;;
    remove)
    ;;
    purge)
        if [ -x /usr/bin/ucf ]; then
           ucf --purge /etc/quanta/agent.yml
        fi
        rm -f /etc/quanta/agent.yml
        rm -Rf /var/run/quanta/

        if getent passwd quanta-agent >/dev/null 2>&1; then
          userdel quanta-agent
        fi
        if getent group quanta-agent >/dev/null 2>&1; then
          groupdel quanta-agent
        fi
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
esac

#DEBHELPER#

exit 0
