#!/bin/sh
### BEGIN INIT INFO
# Provides:          quanta-agent
# Required-Start:    $local_fs $remote_fs $network $named $time $syslog
# Required-Stop:     $local_fs $remote_fs $network $named $time $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       Quanta agent daemon init script
### END INIT INFO

set -e

NAME=quanta-agent
DAEMON=/usr/bin/quanta-agent
CONFIG=/etc/quanta/agent.yml
DESC="Quanta agent"

test -x $DAEMON || exit 0

DIR=/var/run/quanta-agent
PID=$DIR/$NAME.pid

if test ! -d "$DIR"; then
  mkdir $DIR
fi

. /lib/lsb/init-functions

case "$1" in
  start)
    log_daemon_msg "Starting $DESC" "$NAME"
	   start-stop-daemon --oknodo --start --pidfile $PID --exec $DAEMON -- $CONFIG >/dev/null 2>&1
    case "$?" in
        0) log_end_msg 0 ;;
        *) log_end_msg 1; exit 1 ;;
    esac
	;;
  stop)
    log_daemon_msg "Stopping $DESC" "$NAME"
	  start-stop-daemon --oknodo --stop --pidfile $PID --retry $RETRY
    case "$?" in
        0) log_end_msg 0 ;;
        *) log_end_msg 1; exit 1 ;;
    esac
	;;
  status)
    status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
    ;;
  restart|force-reload)
	$0 stop
	$0 start
	;;
  *)
    echo "Usage: /etc/init.d/$NAME {start|stop|restart|force-reload}" >&2
	  exit 1
	;;
esac

exit 0
